config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :conversations
  post 'conversations', to: 'conversations#create'
  post 'messages', to: 'messages#create'

  get 'search_listing', to: 'listings#search_listing'

  get '/listing_review', to: 'listings#review_list'
  post '/listing_review', to: 'listings#review_list'

  mount EpiCas::Engine, at: "/"
  devise_for :users
  
  get '/listings/:id/edit/:image_ids', to: 'listings#delete_image', as: 'delete_image'

  resources :listings do 
    collection do
      get 'validate'
    end
  end

  match "/403", to: "errors#error_403", via: :all
  match "/404", to: "errors#error_404", via: :all
  match "/422", to: "errors#error_422", via: :all
  match "/500", to: "errors#error_500", via: :all

  get :ie_warning, to: 'errors#ie_warning'
  get :javascript_warning, to: 'errors#javascript_warning'

  root to: "listings#index"
  get 'search', to: "listings#search"

  get "/pages/:page" => "pages#show"
  
  get "/moderator", to: "moderator#index"

  resources :categories
  post "/categories/add_category", to: "categories#add_category"
  post "/categories/delete_category", to: "categories#delete_category"

  

  #policy edits
  get "/policies/parse" => "policies#parse"
  get "/policies/:page" => "policies#show"
  get "/policies/edit/:page" => "policies#edit"
  post "/policies/update/:page" => "policies#update"

  get "/users/get_moderators/" => "users#get_moderators"
  get "/users/search/" => "users#search"
  post "/users/grant_moderator/" => "users#grant_moderator"
  post "/users/revoke_moderator/" => "users#revoke_moderator"
  post "/users/ban/" => "users#ban_user"
  post "/users/unban/" => "users#unban_user"
  resources :users
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
# == Schema Information
#
# Table name: listings
#
#  id         :bigint           not null, primary key
#  archived   :boolean          default(FALSE)
#  deleted    :boolean          default(FALSE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_listings_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Listing < ApplicationRecord
  belongs_to :user

  # ===== Static Functions =====
  # Returns all approved listings.
  def self.select_approved_listings
    return Listing.select { |listing| listing.has_approved_version? }
  end

  # Select the last x listings based off date created.
  def self.newest(count)
    ordered_listings = Listing.order(:created_at).select do |listing| 
      listing.has_approved_version?
    end
      
    return ordered_listings.last(count).reverse
  end

  def self.newest_free(count, mask)
    Listing.select{|listing| listing.has_approved_version? and listing.listing_content(approved: true).price == 0.0 and (!mask.include? listing)}.last(count).reverse()
  end

  def self.newest_exchanges(count, mask)
    Listing.select{|listing| listing.has_approved_version? and listing.listing_content(approved: true).get_payment_options().include? "Swap" and (!mask.include? listing)}.last(count).reverse()
  end

  # Select based on search query
  def self.search(only_approved, params)
    listings = Listing.select do |listing|
      listing_content = listing.listing_content(only_approved)
      if listing_content.nil? then next false end # If no content is found then false.
      filters = [] # Array of booleans for all the filters listed here.

      filters.push(!only_approved || listing.has_approved_version?) # Matches Approval Status.
      filters.push(listing_content.match_filter?(
        title= params[:title],
        category= params[:category],
        payment_options= params[:payment_options],
        delivery_options= params[:delivery_options],
        condition= params[:condition_options],
        price_lb= params[:lower_bound_price],
        price_ub= params[:upper_bound_price],
        location_options= params[:location_options]
      )) # Content spesific filtering.

      next filters.all?
    end

    listings.reverse() # Reverse order.

    return listings
  end

  def self.select_listings_by_category_id(category_id)
    Listing.select{|listing| (listing.listing_content.category_id == category_id)}
  end

  # Returns the listing indentified by the given id
  def self.find_listing(id)
    Listing.find(id)
  end
  
  def self.find_listing_by_user(id)
    Listing.where(user_id: id, deleted: false)
  end
  
  # Selects all listings that should be on the moderation queue
  def self.select_pending
    Listing.select {|listing| !listing.deleted && !listing.fully_approved?}
  end

  # Returns a hash for each approved listing
  def self.get_all_listing_hashes
    listings = select_approved_listings
    hashes = []
    listings.each do |listing|
      hashes.push(listing.generate_listing_hash)
    end
    return hashes
  end
  
  # Deletes listing
  def delete_listing
    listing_content.delete_contents
    update(deleted: true)
  end

  # Generates a hash for the specified listing
  def generate_listing_hash
    content = listing_content(approved: true)
    if content.nil?
      content = listing_content
    end
    return {listing: self, content: content, pending: !fully_approved?}
  end

  # ===== Approval Logic =====
  # Check if listing's latest version is approved.
  def fully_approved?
    last_content = ListingContent.where(listing_id: self[:id]).last
    if last_content.nil? then return false end
    return last_content.approved
  end

  # Check if a listing has any approved versions.
  def has_approved_version?
    ListingContent.where(listing_id: self[:id], approved: true).size > 0
  end

  # ===== Listing Content Logic =====
  def listing_content(approved = false)
    listings = nil
    if approved
      listings = ListingContent.where(listing_id: self[:id], approved: true)
    else
      listings = ListingContent.where(listing_id: self[:id])
    end
    return listings.order(:created_at).last
  end

  def get_all_listing_contents
    ListingContent.where(listing_id: self[:id])
  end

  # ===== Ability Logic =====
  def user_can_read?(user)
    return !deleted && ((has_approved_version?) || (!has_approved_version? && (self[:user_id] == user.id)))
  end

  def user_can_update?(user)
    user_id == user.id
  end
end

app/controllers/listings_controller.rb
SHELF_ITEM_COUNT = 6

class ListingsController < ApplicationController

  before_action :find_listing, only: [:edit, :show, :destroy, :update, :delete_image]
  before_action :get_categories, except: [:index, :destroy, :show, :review_list]

  def index
    #Listing selection
    new_listings = Listing.newest(SHELF_ITEM_COUNT)
    free_listings = Listing.newest_free(SHELF_ITEM_COUNT, new_listings)
    exchange_listings = Listing.newest_exchanges(SHELF_ITEM_COUNT, new_listings + free_listings)

    # Shelf Generation
    @shelves = {}
    @shelves["new_listings"] = {content: new_listings, title: "Newest Items", class: "new-listings"}
    @shelves["free_listings"] = {content: free_listings, title: "Free Items", class: "free-listings"}
    @shelves["swap_listings"] = {content: exchange_listings, title: "Swappable Items", class: "swap-listings"}
  end

  def show
    redirect_to root_path, notice: "This listing is not available for viewing" unless can?(:read, @listing)
    @listing_content = @listing.listing_content(approved: true)
    if @listing_content.nil?
      @listing_content = @listing.listing_content
    end

    @urls = @listing_content.image_urls

    @payments = @listing_content.print_payment_options
    @deliveries = @listing_content.print_delivery_options
    @condition = @listing_content.print_condition

    @modified = @listing_content.print_last_modified
    @pending = !@listing.fully_approved?
  end

  def edit
    @mod_editing = !can?(:update, @listing) && current_user.moderator
    redirect_to root_path, notice: "You can't edit this listing" unless (can?(:update, @listing) || @mod_editing)
    @deleted_image_ids = params[:image_ids]
    if @deleted_image_ids.nil?
      @deleted_image_ids = []
    end
  end

  def new
  end

  def create
    listing = Listing.create(user: current_user)
    listing_content = ListingContent.new()
    new_params = listing_params
    selected_category = Category.find_by(name: new_params.delete(:category))
    if !selected_category.nil?
      new_params[:category_id] = selected_category.id
    end
    new_params[:listing_id] = listing.id

    if listing_content.update(new_params)
      redirect_to listing, notice: 'Listing was successfully created.'
    else
      redirect_to new_listing_path, notice: "Couldn't create listing, some of the mandatory options have invalid or empty inputs"
    end

  end

  def update
    if params[:commit].nil?
      ListingContent.where(listing_id: params[:id]).order(created_at: :desc).first.update(approved: true)
      redirect_to listing_review_path, notice: 'Listing was accepted'
    else
      collate_images
      new_listing = ListingContent.new(listing_id: @listing.id)
      if new_listing.update(edit_listing_params)
        redirect_to @listing, notice: 'Listing edition successful, awaiting approval by moderators'
      else
        redirect_to edit_listing_path, notice: 'Edition unsuccessful, some of the non-optional details were blank or invalid'
      end
    end
  end

  def delete_image
    redirect_to edit_listing_path(@listing, image_ids: params[:image_ids].split("/")), notice: 'Image was removed from the listing'
  end

  def destroy
    @listing.delete_listing
    if params[:commit] == "reject"
      redirect_to listing_review_path, notice: 'Listing was rejected and deleted'
    else
      redirect_to root_path, notice: 'Listing was deleted'
    end

  end

  # Get for moderation queue
  def review_list
    redirect_to root_path, notice: "You are not authorized" unless can?(:review_list, Listing)
    @listings_for_approval = Listing.select_pending
    if @listings_for_approval.size != 0
      id = params[:clicked_listing_id]
      if id.nil?
        @current_listing = @listings_for_approval[0]
      else
        @current_listing = Listing.find_listing(id)
      end
      @current_content = @current_listing.listing_content
      @urls = @current_content.image_urls()
    end
  end

  def search
    non_advanced_params = ["title", "category", "button"]
    @is_advanced_search = false
    search_listing_params.each do |param|
      logger.info param
      if !non_advanced_params.include? param[0] then @is_advanced_search = true end
    end
    @search_listings = Listing.search(true, search_listing_params)  
  end

  def search_listing
    if params[:title].strip != ""
      results = Listing.search(true, params)
      result = []
      results.each do |listing|
        result.push(listing.listing_content(approved: true))
      end
      respond_to {|format| format.json {render status: 200, json: {"success" => true, "matches" => result}}}
    else
      respond_to {|format| format.json {render status: 200, json: {"success" => true, "matches" => []}}}
    end
  end

  private
    def listing_params
      params.require(:listing).permit(:title, :description, :category, :price, :location, :condition, :post_code, :terms, delivery_options: [], payment_options: [], images: [])
    end

    def search_listing_params
      params.permit(:title, :category, :button, :lower_bound_price, :upper_bound_price, :commit, location_options: [], payment_options: [], delivery_options: [], condition_options: [])
    end

    def edit_listing_params 
      params.require(:listing_content).permit(:title, :description, :category_id, :price, :location, :condition, :images_to_delete, :post_code, delivery_options: [], payment_options: [], images: [], new_images: [])
    end

    def find_listing
      @listing = Listing.find_listing(params[:id])
      @listing_content = @listing.listing_content
    end

    def get_categories
      @categories = []
      all_categories = Category.get_all.order(:name)
      all_categories.each do |category|
        @categories.push(category.name)
      end
    end
    
    def collate_images
      if !params[:listing_content][:images_to_delete].nil?
        removed_images = params[:listing_content].delete(:images_to_delete).split(" ")
        if !params[:listing_content][:images].nil?
          params[:listing_content][:images].delete_if {|image| removed_images.include? image}
        end
      end
      if params[:listing_content][:new_images].nil?
        params[:listing_content].delete(:new_images)
      else
        new_images = params[:listing_content].delete(:new_images)
        if params[:listing_content][:images].nil?
          params[:listing_content][:images] = new_images
        else
          new_images.each do |image|
            params[:listing_content][:images].push(image)
          end
        end
      end
    end
end

app/views/listings/edit.html.haml
.card
  .card-header
    Edit Listing
  = simple_form_for @listing_content, url: listing_path, html: { data: {cancel_path: listings_path}}, defaults: {class: "listing-input"} do |l|
    .card-body
      %h2 Listing Details
      // Title
      = l.input :title, input_html: {autocomplete: "off",class: 'required-details', id: 'title-field', maxlength: 250}
      #title-limit.text-danger.new-listing-warning
        Title character limit reached
      // Description
      = l.input :description, as: :text, input_html: {class: 'expandable-input required-details', id: 'description-field', maxlength: 2000}
      #description-length-left.new-listing-warning
      // Category
      = l.association :category, input_html: {class: 'listing-select2 required-details'}
      // Price
      = l.input :price, as: :numeric, input_html: {autocomplete: "off",class: 'required-details', id: 'price', min: '0', max: '10000', step: '1'}
      #invalid-price.text-danger.new-listing-warning
        Invalid price: has to be within £0 - £10000 range
        // Location
      = l.input :location, collection: ListingContent::LOCATION_OPTIONS, input_html: {class: 'listing-select2 required-details', id: 'location'}
      #post-code-input
        // Post code (if applicable)
        = l.input :post_code, label: 'Postal Code (First 3 characters)', input_html: {id: 'post-code', maxlength: 3}, type: 'hidden', required: false
        #invalid-post-code.text-danger.new-listing-warning
          Invalid post code
      
      %div
        // Delivery options
        - ListingContent::DELIVERY_OPTIONS.each do |option| 
          - if ((!@listing_content.delivery_options.nil?) && (@listing_content.delivery_options.include? option))
            = check_box :listing_content, :delivery_options, {multiple: true, checked: true, :class=> 'required-options'}, option, nil
          - else
            = check_box :listing_content, :delivery_options, {multiple: true, :class=> 'required-options'}, option, nil
          = option
      %p
      %h2.my-4 Optional Details
      // Moderators cannot edit listing images
      - if !@mod_editing
        %div
          %p
            // Images
            = l.label :photos
            = l.file_field :new_images, multiple: true
      %div
        %br
        = l.hidden_field :images_to_delete, value: @deleted_image_ids
        - @listing_content.images.each do |image|
          - if !(@deleted_image_ids.include? image.signed_id)
            = link_to image_tag("#{rails_blob_path(image.blob, disposition: "image", only_path: true)}", :size => "200x150", :class => 'image_link'), delete_image_path(image_ids: [@deleted_image_ids,[image.signed_id]]), id: "image_link#{image.id}"
            = l.hidden_field :images, multiple: true, value: image.signed_id
      %p
        // Condition
        = l.label :condition
        = l.select :condition, ListingContent::CONDITIONS, {}, {selected: @listing_content.condition, include_blank: true, class: "listing-select2"}
      
      %div
        // Payment options
        - ListingContent::PAYMENT_OPTIONS.each do |option| 
          - if ((!@listing_content.payment_options.nil?) && (@listing_content.payment_options.include? option))
            = check_box :listing_content, :payment_options, {multiple: true, checked: true}, option, nil
          - else
            = check_box :listing_content, :payment_options, {multiple: true}, option, nil
          = option

    .card-footer.d-flex.justify-content-between
      = l.button :submit, class: "btn-primary", id: "edit-button"
      - if can?(:destroy, @listing)
        = link_to listing_path(@listing.id), method: :delete, class: "btn btn-danger rounded-0 view-listing-button", id: "view-listing-delete-button", data: { confirm: "Are you sure you want to delete this listing?" } do
          Delete Listing &nbsp

app/views/listings/new.html.haml
.card
  = content_for(:terms) do
    I've read and accepted the 
    // Redirects to site policies in a new tab
    = link_to 'Terms and Conditions', "/policies/site_policy", target: :_blank

  = simple_form_for :listing, url: listings_path, html: { data: {cancel_path: listings_path}}, defaults: {class: "listing-input"} do |l| # NOTE: cancel_path becomes cancel-path in the data attribute
    .card-body
      #listing-details
        %h2.mb-4 Listing Details
        // Title
        = l.input :title, input_html: {autocomplete: "off", class: 'required-details', id: 'title-field', maxlength: 250}
        #title-limit.text-danger.new-listing-warning
          Title character limit reached
        // Description
        = l.input :description, as: :text, input_html: {class: 'expandable-input required-details', id: 'description-field', maxlength: 2000}
        #description-length-left.new-listing-warning
        // Category
        = l.input :category, collection: @categories, input_html: {class: 'listing-select2 required-details', id: 'test2'},  include_hidden: false
        // Price
        = l.input :price, as: :numeric, input_html: {autocomplete: "off", class: 'required-details', id: 'price', min: '0', max: '10000', step: '1'}
        #invalid-price.text-danger.new-listing-warning
          Invalid price: has to be within £0 - £10000 range
        // Location
        = l.input :location, collection: ListingContent::LOCATION_OPTIONS, input_html: {class: 'listing-select2 required-details', id: 'location'},  include_hidden: false
        #post-code-input
          // Post code if applicable
          = l.input :post_code, label: 'Postal Code (First 3 characters)', input_html: {id: 'post-code', maxlength: 3}, type: 'hidden', required: false
          #invalid-post-code.text-danger.new-listing-warning
            Invalid post code
        // Delivery options
        = l.input :delivery_options, input_html: {class: 'listing-select2 required-details', multiple: "multiple"}, collection: ListingContent::DELIVERY_OPTIONS, include_hidden: false

      #optional-details
        %h2.mb-4 Optional Details
        // Condition
        = l.input :condition, collection: ListingContent::CONDITIONS, include_blank: true, input_html: {class: 'listing-select2'}
        // Payment options
        = l.input :payment_options, collection: ListingContent::PAYMENT_OPTIONS, include_hidden: false, input_html: {class: 'listing-select2', multiple: "multiple"}
        // Images
        = l.input :images, as: :file, input_html: {multiple: true, id: 'images', accept:"image/png, image/jpeg"}
        #error-message.new-listing-warning
        = l.input :terms, as: :fake_checkbox, wrapper: :vertical_boolean, label: content_for(:terms)
    .card-footer
      = l.button :submit, class: "btn-primary", id: "submit-button"
      = l.button :button, "Next", type: "button", name: "next", class: "btn-primary", id: "next-button", style: "display: none"
      = l.button :button, "Another", type: "button", name: "another", class: "btn-primary", id: "another-button", style: "display: none"
      .float-right
        = l.button :button, "Cancel", type: "button", name: "cancel", class: "btn-outline-secondary", id: "cancel-button" # Redirects to listing_path
        = l.button :button, "Back", type: "button", name: "back", class: "btn-outline-secondary", id: "back-button", style: "display: none"

app/views/listings/review_list.html.haml
%h1
  %strong
    Moderation Queue
%hr
%p
- if (@listings_for_approval.size != 0)
  .row
    .col-md-4#review-listing-category.text-break
      //Category, Photo
      %p.text-muted
        = @current_content.category.name
      .w-100
        .square-div
          = link_to "#image-carousel-modal", "data-toggle" => "modal" do
            = image_tag("#{@urls.first}", class: "cropped-image") 
      //User, rating, contact, report
      .mt-3
        .left-right
          %span
            =link_to @current_listing.user.show_user, @current_listing.user

          .btn.stars
            %i.fas.fa-star
            %i.fas.fa-star
            %i.fas.fa-star
            %i.fas.fa-star
            %i.fas.fa-star
    .col-md-5#review-listing-details.text-break
      //Title, price, details      
      %strong
        %h4
          = @current_content.title
      .listing-price
        = @current_content.display_price
      %hr
      %strong
        About this item
      .left-right.mt-3
        %span.text-muted
          %i.fas.fa-clipboard
          Item condition
        %span.text-right
          = @current_content.print_condition
      .left-right.mt-3
        %span.text-muted
          %i.fas.fa-map-marker-alt
          Location
        %span.text-right
          .text-uppercase.d-inline= @current_content.post_code
          = @current_content.location
      .left-right.mt-3
        %span.text-muted
          %i.fas.fa-clock
          Last modified:
        %span.text-right
          = @current_content.print_last_modified
      %p.mt-3
        = @current_content.description
      %hr
      %strong
        Payment & Delivery
      .left-right.mt-3
        %span.text-muted
          %i.fas.fa-credit-card
          Payment options
        %span.text-right
          = @current_content.print_payment_options
      .left-right.mt-3.mb-3
        %span.text-muted
          %i.fas.fa-truck 
          Delivery Options
        %span.text-right
          = @current_content.print_delivery_options

      .left-right
        = link_to listing_path(@current_listing.id), method: :patch, id: "accept_listing#{@current_listing.id}", class: "btn btn-primary rounded-0 review-listing-button", data: { confirm: "Are you sure?" } do
          Approve &nbsp
          %i.fas.fa-check
        = link_to edit_listing_path(@current_listing.id), id: "edit_listing#{@current_listing.id}", class: "btn btn-warning rounded-0 review-listing-button" do
          Edit &nbsp
          %i.fas.fa-edit
        = link_to listing_path(@current_listing.id, commit: 'reject'), method: :delete, id: "reject_listing#{@current_listing.id}", class: "btn btn-danger rounded-0 review-listing-button", data: { confirm: "Are you sure?" } do
          Reject &nbsp
          %i.fas.fa-times
    .col-md-3#review-listing-list
      %h6.text-right.mb-3
        %strong Pending Listings (#{@listings_for_approval.size})
      #review-listing-list-container
        // Add the 'clicked' class to the first link div
        - clicked = ""
        - @listings_for_approval.each do |listing|
          - content = listing.listing_content
          - if @current_listing.id == content.id
            - clicked = " clicked"
          %div{class: "listing_div mb-2#{clicked}"}
            = link_to listing_review_path(:clicked_listing_id => content.listing_id), id: "select_listing#{content.listing_id}", class: "text-dark text-break" do
              .left-right
                .w-25.d-flex.align-items-center
                  .square-div
                    = image_tag("#{content.listing_url}", class: "cropped-image")
                %span.line-clamp-3.w-75.text-left.pl-3= content.title
          - clicked = ""
  = render 'image_carousel'
- else
  %p There are no listings awaiting moderation.

app/views/listings/search.html.haml
%h1 Search Results
%button.btn.btn-primary.collapse.multi-collapse{:class => ("show" unless @is_advanced_search), id: "show-advanced-search", type: "button", "data-toggle" => "collapse", "data-target" => ".multi-collapse", "aria-expanded" => "false", "aria-controls" => "show-advanced-search advanced-search-form"} Advanced Search
.collapse.multi-collapse{id: "advanced_search_form"}
    = form_tag search_path, :method => :get do
        .card-body
            = hidden_field_tag(:title, params[:title])
            = hidden_field_tag(:category, params[:category])
            .form-group.d-flex.flex-row#price
                .d-flex.flex-column.m-2
                    %label{for: "price-lb"} Min Price:
                    .input-group
                        .input-group-prepend
                            %span.input-group-text £
                        = number_field_tag 'lower_bound_price', params[:lower_bound_price], placeholder: '£ Min', min: 0, class: "form-control", id: "price-lb"
                .d-flex.flex-column.m-2
                    %label{for: "price-ub"} Max Price:
                    .input-group
                        .input-group-prepend
                            %span.input-group-text £
                        = number_field_tag 'upper_bound_price', params[:upper_bound_price], placeholder: '£ Max', min: 0, class: "form-control", id: "price-ub"
            // Search filters
            .form-group#payment-options
            %p.m-0 Payment:
            %select{id: "payment-options-select", name: "payment_options[]", multiple: "multiple"}
                - ListingContent::PAYMENT_OPTIONS.each do |payment_option|
                    %option{value: payment_option, selected: (!params[:payment_options].nil? && (params[:payment_options].include? payment_option))} #{payment_option}
            .form-group#delivery-options
            %p.m-0 Delivery:
            %select{id: "delivery-options-select", name: "delivery_options[]", multiple: "multiple"}
                - ListingContent::DELIVERY_OPTIONS.each do |delivery_option|
                    %option{value: delivery_option, selected: (!params[:delivery_options].nil? && (params[:delivery_options].include? delivery_option))} #{delivery_option}
            .form-group#condition-options
            %p.m-0 Condition:
            %select{id: "condition-options-select", name: "condition_options[]", multiple: "multiple"}
                - ListingContent::CONDITIONS.each do |condition_option|
                    %option{value: condition_option, selected: (!params[:condition_options].nil? && (params[:condition_options].include? condition_option))} #{condition_option}
            .form-group#location-options
            %p.m-0 Location:
            %select{id: "location-options-select", name: "location_options[]", multiple: "multiple"}
                - ListingContent::LOCATION_OPTIONS.each do |location_option|
                    %option{value: location_option, selected: (!params[:location_options].nil? && (params[:location_options].include? location_option))} #{location_option}
        
        .card-footer
            - if !@is_advanced_search
                %button.btn.btn-danger{id: "hide-advanced-search", type: "button", "data-toggle" => "collapse", "data-target" => ".multi-collapse", "aria-expanded" => "false", "aria-controls" => "show-advanced-search advanced-search-form"} Hide
            = submit_tag "Apply filters", class: "btn btn-primary"

- if !@search_listings.empty? 
    // Display search results
    .row.justify-content-start
        - @search_listings.each do |listing|
            .col-lg-4.col-md-6.mb-4
                - listing_content = listing.listing_content(approved= true)
                .card.p-3.border-0
                    = link_to listing do
                        .card-body.p-0
                            .square-div.mb-2
                                = image_tag("#{listing_content.listing_url}", class: 'card-img-top cropped-image')
                            .left-right.text-muted.mb-2
                                %span= listing_content.category.name
                                %span.text-secondary= listing_content.display_price
                            %h5.text-dark.line-clamp-2.pb-1= listing_content.title
- else
    %p No results found

app/views/listings/show.html.haml
- if @pending
  %p This listing is awaiting moderation
.row
  .col-md-5.text-break
    //Category, Photo
    %p.text-muted
      = @listing_content.category.name
    .w-100
      .square-div
        = link_to "#image-carousel-modal", "data-toggle" => "modal" do
          = image_tag("#{@urls.first}", class: "cropped-image")   
    //User, rating, contact, report
    .mt-3
      .left-right
        %span
          = link_to @listing.user.show_user, @listing.user

        %button.btn.p-0
          %i.fas.fa-star
          %i.fas.fa-star
          %i.fas.fa-star
          %i.fas.fa-star
          %i.fas.fa-star
      - if @listing.user_id != current_user.id
        %div
          = button_to 'Contact Seller',{:controller => 'conversations', :action => 'create', :seller => @listing.user, :listing => @listing, :buyer => current_user, :method => :post}, { type: 'submit', class: 'btn btn-primary rounded-0 w-100 mt-2 listing-contact-button mb-3', id: 'contact-button' }
          = link_to @listing, class: "text-muted" do
            %i.fas.fa-flag
            Report this item
  .col-md-7.text-break
    //Title, price, details   
    %strong
      %h4
        = @listing_content.title
    .listing-price
      = number_to_currency(@listing_content.price)
    %hr
    %strong
      About this item
    .left-right.mt-3
      %span.text-muted
        %i.fas.fa-clipboard
        Item condition
      %span.align-right
        = @condition
    .left-right.mt-3
      %span.text-muted
        %i.fas.fa-map-marker-alt
        Location
      %span.align-right
        .text-uppercase.d-inline= @listing_content.post_code
        = @listing_content.location
    .left-right.mt-3
      %span.text-muted
        %i.fas.fa-clock
        Last modified
      %span.align-right
        = @modified
    %p.mt-3
      = @listing_content.description
    %hr
    %strong
      Payment & Delivery
    .left-right.mt-3
      %span.text-muted
        %i.fas.fa-credit-card
        Payment options
      %span.text-right
        = @payments
    .left-right.mt-3.mb-3
      %span.text-muted
        %i.fas.fa-truck 
        Delivery Options
      %span.text-right
        = @deliveries
    .d-flex.justify-content-end
      - if can?(:update, @listing) || current_user.moderator
        = link_to edit_listing_path(@listing), class: "btn btn-warning rounded-0 view-listing-button" do
          Edit &nbsp
          %i.fas.fa-edit
      - if can?(:destroy, @listing)
        = link_to listing_path(@listing.id), method: :delete, class: "btn btn-danger rounded-0 view-listing-button", id: "view-listing-delete-button", data: { confirm: "Are you sure you want to delete this listing?" } do
          Delete &nbsp
          %i.fas.fa-times
= render 'image_carousel'