config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :conversations
  post 'conversations', to: 'conversations#create'
  post 'messages', to: 'messages#create'

  get 'search_listing', to: 'listings#search_listing'

  get '/listing_review', to: 'listings#review_list'
  post '/listing_review', to: 'listings#review_list'

  mount EpiCas::Engine, at: "/"
  devise_for :users
  
  get '/listings/:id/edit/:image_ids', to: 'listings#delete_image', as: 'delete_image'

  resources :listings do 
    collection do
      get 'validate'
    end
  end

  match "/403", to: "errors#error_403", via: :all
  match "/404", to: "errors#error_404", via: :all
  match "/422", to: "errors#error_422", via: :all
  match "/500", to: "errors#error_500", via: :all

  get :ie_warning, to: 'errors#ie_warning'
  get :javascript_warning, to: 'errors#javascript_warning'

  root to: "listings#index"
  get 'search', to: "listings#search"

  get "/pages/:page" => "pages#show"
  
  get "/moderator", to: "moderator#index"

  resources :categories
  post "/categories/add_category", to: "categories#add_category"
  post "/categories/delete_category", to: "categories#delete_category"

  

  #policy edits
  get "/policies/parse" => "policies#parse"
  get "/policies/:page" => "policies#show"
  get "/policies/edit/:page" => "policies#edit"
  post "/policies/update/:page" => "policies#update"

  get "/users/get_moderators/" => "users#get_moderators"
  get "/users/search/" => "users#search"
  post "/users/grant_moderator/" => "users#grant_moderator"
  post "/users/revoke_moderator/" => "users#revoke_moderator"
  post "/users/ban/" => "users#ban_user"
  post "/users/unban/" => "users#unban_user"
  resources :users
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/moderator_controller.rb
class ModeratorController < ApplicationController
  
  def index
    @current_user_id =  current_user[:id]

    redirect_to root_path, notice: "You are not authorized" unless can?(:review_list, Listing)
    @categories = Category.get_all.order(:name)
    @listings_to_moderate = Listing.select_pending.size
    @all_listings = Listing.get_all_listing_hashes
  end
end

app/views/moderator/_edit_listings.html.haml
.modal.hide.fade#edit_listings{:role => "dialog", :aria-hidden => "true"}
    .modal-dialog.modal-dialog-centered{:role => "document"}
        .modal-content
            .modal-header
                .d-flex.w-100.justify-content-between
                    %h4.modal-title Edit listings
                    // Loading spinner
                    .spinner-border#edit_listing_lookup_spinner{ :role => "status"}
                        %span.sr-only Loading...
                %button.close{data: {dismiss: "modal"}}
                    %i.fas.fa-times
            .modal-body
                %form#listing_search_form
                    .form-group.row.justify-content-around
                        .flex-grow-1.mx-3
                            .input-group                        
                                .input-group-prepend
                                    %label.input-group-text Search
                                %input.form-control#edit-listings-title_input{:placeholder => "Title", "aria-label" => "Title", :name => "title", :autocomplete =>"off"}
                                .input-group-append
                                    %button.btn.btn-originalSecondary#edit-listings-search_button{:type=>"Button", :onclick=>"listing_search()", "aria-label" => "Search Button"}
                                        %i.fas.fa-search

            .table-responsive.moderator-function-table
                %table.table.table-striped.mt-2
                    %tbody#listing_tbody	
                    // Search results will be appended to this table

            .modal-footer
                %button.btn.btn-secondary{:type=>"button", "data-dismiss"=>"modal"}Close

app/views/moderator/_lookup_users.html.haml
.modal.hide.fade#lookup_users{:role => "dialog", :aria-hidden => "true", :data_id => @current_user_id }
	.modal-dialog.modal-dialog-centered.modal-lg{:role => "document"}
		.modal-content
			.modal-header
				.d-flex.w-100.justify-content-between
					%h4.modal-title Lookup users
					// Loading spinner
					.spinner-border#lookup_spinner{ :role => "status"}
						%span.sr-only Loading...
				%button.close{data: {dismiss: "modal"}}
					%i.fas.fa-times
			.modal-body
				%form#lookup_form
					.form-group.row.justify-content-around
						.flex-grow-1.mx-3
							.input-group#lookup_input_group                        
								.input-group-prepend
									%label.input-group-text Search
								%input.form-control#query_input{:placeholder => "Name, username or email", "aria-label" => "Name, username or email", :name => "query_input", :autocomplete =>"off"}
								.input-group-append
									%button.btn.btn-originalSecondary#search_button{:type=>"Button", :onclick=>"user_search()", "aria-label" => "Search Button"}
										%i.fas.fa-search
			.table-responsive.moderator-function-table
				%table.table.table-striped.mt-2
					%tbody#user_lookup_tbody
					// Search results will be appended to this table



			.modal-footer.justify-content-between
				%p Click name to reveal email
				.row
					.mx-3
						%button.btn.btn-outline-primary{:type=>"Button", :onclick=>"show_moderators()"} Show moderators
					%button.btn.btn-secondary{:type=>"button", "data-dismiss"=>"modal"}Close

app/views/moderator/_manage_categories.html.haml
.modal.hide.fade#manage_categories{:role => "dialog", :aria-hidden => "true"}
    .modal-dialog.modal-dialog-centered{:role => "document"}
        .modal-content
            .modal-header
                %h4.modal-title Manage Categories
                %button.close{data: {dismiss: "modal"}}
                    %i.fas.fa-times
            .modal-body
                // Alerts for adding/deleting categories
                .environment-notive.alert.alert-info#categories_submit_alert Category added!
                .environment-notive.alert.alert-info#categories_delete_alert Category deleted!
                %form
                    .form-group
                        %label 
                            %strong Add new category
                        .left-right
                            %input.form-control#manage_categories_name_input{:placeholder => "Category Name", :name => "category_name"}
                            %button.btn.btn-primary#manage_categories_add_button.ml-2{:type => "button"}
                                %i.fas.fa-plus
                            %button.btn.btn-outline-danger#enable_deleting.ml-2{:type => "button", :onclick => "enable_delete_buttons()"}
                                %i.fas.fa-minus
                %hr.mt-4
                %strong Category list
                .table-responsive.moderator-function-table
                    %table.table.table-sm.table-striped.mt-2
                        %tbody#manage_categories_tbody
                            // Category list
                            - @categories.each do |category|
                                %tr
                                    %td.align-middle=category.name
                                    %td.align-middle.text-right
                                        %button.btn-sm.btn-danger.category_delete_btn{:id => category.id, :title => "Delete", :onclick => "delete_category(event)", :data => {"category": - category.name}}
                                            %i.fas.fa-minus
            .modal-footer
                %button.btn.btn-secondary{:type=>"button", "data-dismiss"=>"modal"}Close

app/views/moderator/_template.html.haml
// Replace template with name of the modal function
.modal.hide.fade#template{:role => "dialog", :aria-hidden => "true"}
    .modal-dialog.modal-dialog-centered{:role => "document"}
        .modal-content
            .modal-header
                %h4.modal-title Template title 
                %button.close{data: {dismiss: "modal"}}
                    %i.fas.fa-times
            .modal-body 
                template body
            .modal-footer
                .button.btn.btn-primary button

app/views/moderator/index.html.haml
.row.justify-content-between
    .col-lg-2#moderator-utilities.bg-super-light-green
        .d-flex.flex-column
            %h2
                %strong Utilities
            = button_to "Review Listings (#{@listings_to_moderate})", listing_review_path, {class: "btn btn-primary w-100 mt-3"}
            // NOT IMPLEMENTED:
            %button.btn.btn-primary.mt-3 Listing Reports (0)
            // NOT IMPLEMENTED:
            %button.btn.btn-primary.mt-3 Chat Reports (0)
            = link_to "Lookup User", "#lookup_users", "data-toggle" => "modal", "data-backdrop" => "static", class: "btn btn-primary mt-3"
            = link_to "Edit listings", "#edit_listings", "data-toggle" => "modal", "data-backdrop" => "static", class: "btn btn-primary mt-3"
            %br/
            = link_to "Edit Categories", "#manage_categories", "data-toggle" => "modal", "data-backdrop" => "static", class: "btn btn-primary mt-3"
            = link_to "Site Message", "#template", "data-toggle" => "modal", "data-backdrop" => "static", class: "btn btn-primary mt-3"
            = link_to "Edit Site Policy", url_for(controller: 'policies', action: 'edit', page: 'site_policy'), class: "btn btn-primary mt-3"
            = link_to "Edit COVID Policy", url_for(controller: 'policies', action: 'edit', page: 'covid-19'), class: "btn btn-primary mt-3"
    .col-lg-9#moderator-statistics.bg-super-light-green
        .row
            .col-lg-3 
                %h2
                    // NOT IMPLEMENTED:
                    %strong Statistics
            .col-lg-9
// Render all of the required modals. Much easier to do & test this than to render through javascript
= render 'template'
= render 'manage_categories'
= render 'edit_listings'
= render 'lookup_users'