config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :conversations
  post 'conversations', to: 'conversations#create'
  post 'messages', to: 'messages#create'

  get 'search_listing', to: 'listings#search_listing'

  get '/listing_review', to: 'listings#review_list'
  post '/listing_review', to: 'listings#review_list'

  mount EpiCas::Engine, at: "/"
  devise_for :users
  
  get '/listings/:id/edit/:image_ids', to: 'listings#delete_image', as: 'delete_image'

  resources :listings do 
    collection do
      get 'validate'
    end
  end

  match "/403", to: "errors#error_403", via: :all
  match "/404", to: "errors#error_404", via: :all
  match "/422", to: "errors#error_422", via: :all
  match "/500", to: "errors#error_500", via: :all

  get :ie_warning, to: 'errors#ie_warning'
  get :javascript_warning, to: 'errors#javascript_warning'

  root to: "listings#index"
  get 'search', to: "listings#search"

  get "/pages/:page" => "pages#show"
  
  get "/moderator", to: "moderator#index"

  resources :categories
  post "/categories/add_category", to: "categories#add_category"
  post "/categories/delete_category", to: "categories#delete_category"

  

  #policy edits
  get "/policies/parse" => "policies#parse"
  get "/policies/:page" => "policies#show"
  get "/policies/edit/:page" => "policies#edit"
  post "/policies/update/:page" => "policies#update"

  get "/users/get_moderators/" => "users#get_moderators"
  get "/users/search/" => "users#search"
  post "/users/grant_moderator/" => "users#grant_moderator"
  post "/users/revoke_moderator/" => "users#revoke_moderator"
  post "/users/ban/" => "users#ban_user"
  post "/users/unban/" => "users#unban_user"
  resources :users
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_environment_notice.html.haml
- if display_environment_notice?
  .environment-notice.alert.alert-info
    %strong Notice:
    This is the
    %strong= Rails.env
    system.

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title UoS Marketplace - #{content_for(:title)}
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
    %meta{ :'http-equiv' => 'X-UA-Compatible', content: 'IE=edge' }
    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "content-type"}
    = stylesheet_link_tag    "application", media: :all
    = javascript_include_tag "application"
    = favicon_link_tag "/favicon.ico"
    = csrf_meta_tags

  %body{ class: "#{environment_notice_body_class} #{controller_name} #{action_name}"}
    .flash-messages
      - flash.each do |name, msg|
        - next unless name == 'alert' || name == 'notice'
        .alert.fade.in
          .container
            - if name == 'notice'
              = icon('fas', 'check', class: 'flash-success')
            - else
              = icon('fas', 'exclamation-triangle', class: 'flash-error')
            = msg
            %a{ href: '#', title: 'Hide this message', data: { dismiss: :alert } }
              Dismiss

    #wrap
      %header
        %nav#main-nav.navbar.navbar-dark.bg-dark-green.navbar-expand-lg.fixed-top
          .container
            .navbar-header
              = link_to :root, class: 'navbar-brand hidden-sm' do
                UoS Marketplace
            %button.navbar-toggler{ aria: { controls: "navbar-content", expanded: false, label: "Toggle navigation" }, data: { target: "#navbar-content", toggle: "collapse" }, type: "button" }
              %span.navbar-toggler-icon
            .collapse.navbar-collapse#navbar-content
              - if user_signed_in?
                %ul.nav.navbar-nav.ml-auto
                  - if can?(:review_list, Listing)
                    %li.nav-item
                      = link_to moderator_path, id: "navbar-moderator-link", class: 'nav-link', role: 'button' do
                        = icon 'fas', 'shield-alt', 'Moderator Dashboard'
                  %li.nav-item
                    = link_to conversations_path, class: 'nav-link' do
                      = icon 'fas', 'comments', 'Conversations'
                  %li.nav-item.dropdown
                    = link_to '#', aria: { haspopup: true, expanded: false }, data: { toggle: :dropdown }, id: 'navbar-user-link', class: 'nav-link dropdown-toggle', role: 'button' do
                      = icon 'fas', 'user', current_user.givenname
                      %b.caret
                    .dropdown-menu{ aria: { labelledby: '#navbar-user-link' } }
          
                      = link_to user_path(id: current_user[:id]), class: 'dropdown-item', method: :get, title: "Your Profile" do
                        = icon 'fas', 'user', 'Your Profile'

                      = link_to "/listings/new", class: "dropdown-item", title: "Add Listing" do
                        = icon 'fas', 'plus', 'Add Listing'
                        
                      = link_to destroy_user_session_path, class: 'dropdown-item', method: :delete, title: "Log out of the system" do
                        = icon 'fas', 'sign-out-alt', 'Log out'
      #spacer-box
      - if user_signed_in?
        #container-bar.bg-light-green
          .container
            .searchbar
              = form_tag search_path, :method => :get, :class => 'd-flex justify-content-center' do
                = select_tag "category", options_from_collection_for_select(Category.get_all, "id", "name", params[:category]), include_blank: "All categories", id: "search-bar-categories"
                = text_field_tag(:title, params[:title], placeholder: 'Search', id: "searchbar-field", class: "form-control", autocomplete: 'off')
                = button_tag :submit, id: "search-bar-button", class: "bg-super-light-green" do
                  %i.fas.fa-search

      = render 'layouts/environment_notice'

      %main
        #main-container.container

          = yield
      %footer.footer
        .container.d-flex.flex-row.justify-content-between
          %span.texted-muted.now.text-nowrap
            University of Sheffield
          .float-right
            = link_to "/policies/site_policy" do
              Site Policies        
            = link_to "/policies/covid-19", class: "mx-4" do
              COVID-19 Guidance

app/views/layouts/plain_error.html.haml
!!!
%html
  %head
    %title SoftwareHutProject - #{content_for(:title)}
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
    %meta{ :'http-equiv' => 'X-UA-Compatible', content: 'IE=edge' }
    = stylesheet_link_tag    "application", media: :all
    = javascript_include_tag "application"
    = favicon_link_tag "/favicon.ico"

  %body{ class: environment_notice_body_class }
    = render 'layouts/environment_notice'
    .flash-messages
      - flash.each do |name, msg|
        - next unless name == 'alert' || name == 'notice'
        .alert.fade.in
          .container
            - if name == 'notice'
              = icon('fas', 'check', class: 'flash-success')
            - else
              = icon('fas', 'warning', class: 'flash-error')
            = msg
            %a{ href: '#', title: 'Hide this message', data: { dismiss: :alert } } Dismiss


    %noscript
      .warning-page-cover
        .alert.alert-info
          %h2 Sorry, it appears that you are using a web browser without JavaScript which prevents us offering you a rich online experience.
          %p Please enable JavaScript or use a different web browser, or alternatively contact the CiCS Helpdesk for assistance.

    #wrap
      %nav#main-nav.navbar.navbar-default.navbar-fixed-top
        .container
          .navbar-header
            %button.navbar-toggle{ data: { target: ".navbar-collapse", toggle: :collapse, type: :button } }
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            = link_to :root, class: 'navbar-brand hidden-sm' do
              SoftwareHutProject

          .collapse.navbar-collapse
            %ul.nav.navbar-nav
              = navbar_link_to :root, title: "Go to the home page", identifier: :home do
                = icon 'fas', 'home'
                Home

      #main-container.container

        = yield

    %footer#footer
      .container
        %p
          &copy;#{Date.today.year}
          = link_to 'epiGenesys', 'https://www.epigenesys.org.uk', target: '_blank', title: 'Goto the epiGenesys website'